### ISSUE TITLE
KeyError using FLOWER_BASIC_AUTH

### ISSUE THREAD

**Issue by henrybaxter** [mher/flower#493] opened 2015-11-23 18:48 UTC
With a new virtualenv, latest flower, and the command:

    FLOWER_BASIC_AUTH=admin:123 celery flower

The result is a KeyError (full stack trace below). I believe that the underscores in the environment variable must be replaced with dashes to match the defined options, and further that the map (when an option is a multiple) must be list-ified. I'll send a pull request to fix this issue.

```
(test)me:flower henry$ git rev-parse HEAD
5bd860e6fa20a80a7ca074d3951fe70d2f2d03d3
(test)me:flower henry$ python -V
Python 3.5.0
(test)me:flower henry$ pip freeze
amqp==1.4.7
anyjson==0.3.3
Babel==2.1.1
billiard==3.3.0.21
celery==3.1.19
flower==0.9.0
kombu==3.0.29
pytz==2015.7
tornado==4.3
wheel==0.24.0
```

```
Traceback (most recent call last):
  File "/Users/henry/.virtualenvs/test/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/Users/henry/.virtualenvs/test/lib/python3.5/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/Users/henry/.virtualenvs/test/lib/python3.5/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/Users/henry/.virtualenvs/test/lib/python3.5/site-packages/celery/bin/celery.py", line 770, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/henry/.virtualenvs/test/lib/python3.5/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/Users/henry/.virtualenvs/test/lib/python3.5/site-packages/celery/bin/celery.py", line 762, in handle_argv
    return self.execute(command, argv)
  File "/Users/henry/.virtualenvs/test/lib/python3.5/site-packages/celery/bin/celery.py", line 694, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/Users/henry/.virtualenvs/test/lib/python3.5/site-packages/flower/command.py", line 36, in run_from_argv
    option = options._options[name]
KeyError: 'basic_auth'
```

**Comment by mher** [comment] 2016-01-18 02:06
Duplicate of #489

**Closed by mher** 2016-01-18 02:06 UTC
Labels: duplicate
