### ISSUE TITLE
HTTP Basic Authentication error "KeyError: 'user_name'"

### ISSUE THREAD

**Issue by josh-devops-center** [mher/flower#467] opened 2015-09-15 08:59 UTC
Hello,

Following the example [here](http://flower.readthedocs.org/en/latest/auth.html#http-basic-authentication) receive the following key error when starting flower.

```
Traceback (most recent call last):
  File "/usr/local/opt/python/bin/flower", line 11, in <module>
    sys.exit(main())
  File "/usr/local/opt/python/lib/python2.7/site-packages/flower/__main__.py", line 11, in main
    flower.execute_from_commandline()
  File "/usr/local/opt/python/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/opt/python/lib/python2.7/site-packages/flower/command.py", line 100, in handle_argv
    return self.run_from_argv(prog_name, argv)
  File "/usr/local/opt/python/lib/python2.7/site-packages/flower/command.py", line 39, in run_from_argv
    option = options._options[name]
KeyError: 'user_name'
```

**Comment by mher** [comment] 2015-09-19 14:40
How do you run flower?

**Comment by josh-devops-center** [comment] 2015-09-20 15:31
```
flower --basic_auth=celery:flower
```

**Comment by linaksa** [comment] 2015-10-10 05:38
I am getting the same error message, any solution or workaround available?

Python 3.4.3
Celery 3.1.18 (Cipater)
Flower 0.9.0-dev and 0.8.3

**Comment by henrybaxter** [comment] 2015-11-23 18:20
Do you have FLOWER_USER_NAME set as an environment variable?

**Comment by mher** [comment] 2016-01-18 02:10
Duplicate of #489

**Closed by mher** 2016-01-18 02:10 UTC
Labels: duplicate
