### ISSUE TITLE
Search option Not Working correctly

### ISSUE THREAD

**Issue by sandeepgk1989** [mher/flower#502] opened 2015-12-16 06:34 UTC
Hi Folks, i tried to search a keyword in the new search box and it thrown me some error.

flower   -> flower:0.9.0-dev tornado:4.0.1 babel:2.0
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.6
            billiard:3.3.0.20 py-amqp:1.4.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1332, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 2601, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flower/views/tasks.py", line 88, in get
    search=search
  File "/usr/local/lib/python2.7/site-packages/flower/views/__init__.py", line 20, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 665, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 772, in render_string
    return t.generate(**namespace)
  File "/usr/local/lib/python2.7/site-packages/tornado/template.py", line 278, in generate
    return execute()
  File "tasks_html.generated.py", line 225, in _tt_execute
    for uuid, task in tasks:  # tasks.html:151 (via base.html:49)
  File "/usr/local/lib/python2.7/site-packages/flower/utils/tasks.py", line 46, in iter_tasks
    if not satisfies_search_terms(task, any_value_search_term, result_search_term, args_search_terms, kwargs_search_terms):
  File "/usr/local/lib/python2.7/site-packages/flower/utils/search.py", line 32, in satisfies_search_terms
    any_value_search_term and any_value_search_term in '|'.join([task.args, task.kwargs, str(task.result)]),
TypeError: sequence item 0: expected string, NoneType found

**Comment by cralston-prism** [comment] 2016-01-09 00:15
Duplicate of #480

**Closed** 2016-01-18 21:37 UTC
