### ISSUE TITLE
API Output Incorrect

### ISSUE THREAD

**Issue by nstanoszek** [mher/flower#393] opened 2015-05-11 18:32 UTC
When I use Flower on Ubuntu 14.04, the output of the /api/workers is different than when I run it on a Windows machine.  I am running both locally (i.e. 127.0.0.1:5555).  The windows output is what I would expect based on the API reference docs.  The ubuntu output is extremely close to rabbitmq API.

Any thoughts?  What Am I doing wrong?

Thanks!

**Comment by remotesyssupport** [comment] 2015-05-14 19:12
just a pointer, is it related to the this issue: https://github.com/mher/flower/issues/383. please look at that discussion. Also the api output has changed from version 0.8, so kindly do check the version of flower

**Comment by mher** [comment] 2015-07-28 04:44
Duplicate of #383

**Closed by mher** 2015-07-28 04:44 UTC
Labels: duplicate
