### ISSUE TITLE
Don't print settings in production

### ISSUE THREAD

**Issue by dbrgn** [mher/flower#279] opened 2014-09-18 09:00 UTC
I got this in production:

![screenshot](http://tmp.dbrgn.ch/screenshots/20140918_105858.png)

According to the `--help` output, `--debug` is False by default. In that case no potentially security relevant information should be printed to the browser.

**Comment by mher** [comment] 2016-03-05 21:48
Duplicate of #340

**Closed** 2016-03-05 21:48 UTC
Labels: duplicate
