### ISSUE TITLE
No match found while searching a string

### ISSUE THREAD

**Issue by Rajlaxmi** [mher/flower#549] opened 2016-03-15 06:45 UTC
Hi,

Whenever I try to search a string by putting the text in Search box, I get the following error.
Can you rectify this?
```

flower   -> flower:0.8.3 tornado:4.3 babel:2.1.1
software -> celery:3.1.19 (Cipater) kombu:3.0.29 py:2.7.10
            billiard:3.3.0.21 py-amqp:1.4.7
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:amqp

CELERY_ACKS_LATE: True
CELERY_STORE_ERRORS_EVEN_IF_IGNORED: False
CELERY_TASK_RESULT_EXPIRES: 600
CELERYD_TASK_TIME_LIMIT: 3600
CELERY_EVENT_QUEUE_TTL: 1200
CELERYD_PREFETCH_MULTIPLIER: 1
BROKER_URL: 'amqp://mainClient:********@52.91.139.132:5672/vhostClient'
CELERY_RESULT_BACKEND: 'amqp'

Traceback (most recent call last):
  File "/usr/local/lib64/python2.7/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib64/python2.7/site-packages/tornado/web.py", line 2800, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flower-0.8.3-py2.7.egg/flower/views/tasks.py", line 88, in get
    search=search
  File "/usr/local/lib/python2.7/site-packages/flower-0.8.3-py2.7.egg/flower/views/__init__.py", line 20, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/usr/local/lib64/python2.7/site-packages/tornado/web.py", line 699, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib64/python2.7/site-packages/tornado/web.py", line 806, in render_string
    return t.generate(**namespace)
  File "/usr/local/lib64/python2.7/site-packages/tornado/template.py", line 345, in generate
    return execute()
  File "tasks_html.generated.py", line 225, in _tt_execute
    for uuid, task in tasks:  # tasks.html:151 (via base.html:49)
  File "/usr/local/lib/python2.7/site-packages/flower-0.8.3-py2.7.egg/flower/utils/tasks.py", line 46, in iter_tasks
    if not satisfies_search_terms(task, any_value_search_term, result_search_term, args_search_terms, kwargs_search_terms):
  File "/usr/local/lib/python2.7/site-packages/flower-0.8.3-py2.7.egg/flower/utils/search.py", line 32, in satisfies_search_terms
    any_value_search_term and any_value_search_term in '|'.join([task.args, task.kwargs, str(task.result)]),
TypeError: sequence item 0: expected string, NoneType found
```

**Comment by mher** [comment] 2016-03-19 04:02
Duplicate of #480

**Comment by mher** [comment] 2016-03-19 04:03
This issue is already fixed. Try to update to the latest version or use the master version

**Closed by mher** 2016-03-19 04:03 UTC
Labels: duplicate
