### ISSUE TITLE
[Enhancement suggestion] Make a "read only" mode

### ISSUE THREAD

**Issue by TheBlusky** [mher/flower#898] opened 2019-04-26 07:57 UTC
I need to give access to flower to some users in order to investigate tasks (for bug and support). However, Flower would give too much control over the environement (ability to revoke tasks and remove workers).

Would it be interesting to add a configuration option like "read-only-mode" that would prevent users from doing harmful operation ?

In order to do this, I found out two things to do:
- For the backend, there is only the `ControlHandler` (https://github.com/mher/flower/blob/master/flower/api/control.py) to remove.
That might be easily done by adding a new decorator to all `@web.authenticated` within this file.
- For the frontend, it might be faster, just to handle an "unauthoized request" response (better ask forgiveness than permission policy), however, a better UX would be to remove concerned forms from templates.

Would a PR implementing this be acceptable ?

**Comment by mher** [comment] 2019-05-10 10:13
Duplicate of #117

**Closed** 2019-12-29 19:14 UTC
Labels: duplicate, enhancement
