### ISSUE TITLE
flower with persistent & db not starting

### ISSUE THREAD

**Issue by jheld** [mher/flower#713] opened 2017-06-27 15:55 UTC
My team is trying to use the persistent mode and flower will fail to start when doing so. We add `--persistent=True --db=flower` and that's when trouble occurs.

We are running on v0.9.2 with celery 4. Any ideas?

**Comment by rcguerrra** [comment] 2017-07-18 19:03
+1
Same problem

**Comment by rromanotero** [comment] 2017-08-10 01:27
I checked issue #723 and it's marked as duplicate of this issue (#713). Now I'm going in circles, or I'm missing something. Sorry, my team is just having the same problem. Thank you.

**Comment by jheld** [comment] 2017-09-25 12:53
@mher Would you be able to point me to the section of code that `persistent` deals with? Aside from learning the code more, my team really needs this fixed, and as such a quick primer to the source would make it easier for me.

**Comment by mher** [comment] 2017-09-25 16:29
@jheld https://github.com/mher/flower/blob/master/flower/events.py#L75

**Comment by jheld** [comment] 2017-09-25 20:10
@mher OK, so I can use the `--persisted=1` flag in the CLI. And I can specifically use `CELERYD_SEND_EVENTS = True` in my settings.

My confusion about whether flower even worked with persisted was where the data would show. I didn't realize it was buried under the `Tasks` page, which now makes a ton of sense. I think I'll make a PR to the docs to make it explicit.

I'll try to test the persistent & flower starting issue this week and will update on my findings.

**Comment by jheld** [comment] 2018-05-03 00:16
Has anyone had issues where flower wouldn't start because of a runtime error possibly related to reading the persisted db?

**Comment by sshishov** [comment] 2019-08-25 01:00
Runtime error should be fixed by this change: https://github.com/celery/celery/pull/5694

**Comment by mher** [comment] 2019-12-30 09:36
Works with `celery >= 4.4.0`

**Comment by jheld** [comment] 2019-12-30 13:36
It's fine to close this, although we got around it eventually by using #821 . This issue might still be real but since no one has reproduced on python2.7 (the celery fix was for py3) as far as I'm aware, makes sense to close. We're on py3.7 at this time anyway.

**Comment by mher** [comment] 2020-05-08 03:18
thanks @jheld

**Closed** 2020-05-08 03:18 UTC
