### ISSUE TITLE
How to Monitor celery task status of multiple projects in single celery flower.

### ISSUE THREAD

**Issue by swethanaretla** [mher/flower#521] opened 2016-02-02 13:03 UTC
Hi,
I have Followed flower celery document for monitoring tasks status with rabbitmq-server for one project. Its working fine, but i am unable to monitor two different servers tasks with different broker url, is this possible?
Used same rabbitmq with different vhosts
project X:
Broker_url_x="amqp://username:password@host:5672//vhost1" 
project Y:
Broker_url_y="amqp://username:password@host:5672//vhost2"

I am able to monitor only one project's task in flower
sudo celery flower --broker=Broker_url_x Broker_url_y

Could you please provide me some advice:_)

**Comment by mher** [comment] 2016-02-07 01:07
Duplicate of #111

**Closed** 2016-02-07 01:08 UTC
Labels: duplicate
