### ISSUE TITLE
Tornado no longer has asynchronous decorator

### ISSUE THREAD

**Issue by 2stacks** [mher/flower#878] opened 2019-02-19 19:49 UTC
Looks like Tornado dropped this decorator in the latest release v6.0.0b1.

When trying to run 'celery flower' last message in stack trace is;

AttributeError: module 'tornado.web' has no attribute 'asynchronous'

**Comment by jml** [comment] 2019-03-01 17:51
AFAICT, this is fixed in code (see https://github.com/mher/flower/blob/master/requirements/default.txt), but that fix has not been released. In fact, there hasn't been a release for a year and a half (https://pypi.org/project/flower/#history), which makes me wonder whether I'm looking at the wrong page.

**Comment by steverecio** [comment] 2019-03-02 21:58
Is there a fix for this? I have flower pinned but this just took down my site

**Comment by steverecio** [comment] 2019-03-02 22:07
Had to add this to requirements.txt after flower:

`tornado>=4.2.0,<6.0.0`

**Comment by 2stacks** [comment] 2019-03-02 23:02
I guess you could also install from main source branch but I also just
locked my requirements.

**Comment by stevenmanton** [comment] 2019-03-03 21:10
This dependency issue breaks stuff for me too. I wonder if there are any plans to release a new tagged version soon. Otherwise all the downstream projects will have to add hacks like @steverecio had to do with Astronomer.

**Comment by mher** [comment] 2019-03-04 10:12
I’m planning to release a new version next week

**Comment by rmagee** [comment] 2019-03-04 19:40
Seeing this as well.  Thanks.

**Comment by shaohua** [comment] 2019-03-05 05:50
10 hours spent on this issue as well

**Comment by josiah14** [comment] 2019-03-05 20:19
This issue broke our Airflow build, today, since we are using Celery.  Thanks, @2stacks for logging the issue, and @jml for identifying the cause.

I (very) strongly recommend adopting the practice of placing an upper bound on the versions of the dependencies your importing.  Otherwise, any bump in one of those dependencies to the next major version is highly likely to break your code (which is exactly what caused this issue).  As far as I can tell looking through the dependencies in the requirements directory, there's no upper-bound placed on any of the versions of the dependencies declared for this project.

**Comment by astleychen** [comment] 2019-03-07 06:59
@josiah14 totally agreed. Hopefully, the new release is coming soon so that I don't need to rollback to 0.9.1 as a workaround. Thanks.

**Comment by josiah14** [comment] 2019-03-08 19:36
@astleychen As a work-around, you can take advantage of the fact that Pip only allows one version of a library to be installed at a time.  So, you could `pip install flower` and then `pip install "tornado<6.0.0"`, as @steverecio pointed out in [this comment](https://github.com/mher/flower/issues/878#issuecomment-468964963).

**Comment by josiah14** [comment] 2019-03-09 01:34
https://github.com/mher/flower/pull/889

**Comment by nirorman** [comment] 2019-03-11 12:57
#MeToo

**Comment by browniebroke** [comment] 2019-03-11 14:15
You don't need Flower (or Celery/Django/<insert your favourite lib here>) to restrict anything, if you run a serious project, you should not depend on your dependencies to restrict their dependencies. If tomorrow Tornado 7 comes out and is fine with Flower, restricting it would prevent you from upgrading your Tornado app, until Flower updates.

Bottom line: you should lock all your dependencies (direct and indirect) yourself in your project. There are tools out there to do that, [pip-tools](https://github.com/jazzband/pip-tools) is a simple solution I recommend ([Pipenv](https://github.com/pypa/pipenv) & [Poetry](https://github.com/sdispater/poetry) do that too). You specify your direct dependencies with version ranges, and this tool generates a requirements.txt file with **everything** pinned.

**Comment by josiah14** [comment] 2019-03-12 04:15
@browniebroke So, you're saying it's not the project maintainers' responsibility to version the project dependencies in a way that maintains the ongoing stability of the project?

If the project no longer builds against the declared versions of its dependencies, it's broken.  Putting an upper bound on the next major version is generally considered a best practice for this reason.

**Comment by astutejoe** [comment] 2019-03-12 04:38
@josiah14 I think his point is that you should only pin a dependency if something breaks and keep watching for fixes so you can unpin it. Locking indefinitely or just for the sake of it, is a bad practice. In my case, I caught this in the staging environment (local environment didn't have the update), fixed it, rolled the fix, done. Only 1 pinned down dependency, tornado, which I plan to unpin when the promised update is released. A even better practice in my case would be always updating my local environment so I can catch the problem even earlier, then pinning and locking dependencies.

**Comment by josiah14** [comment] 2019-03-12 04:44
@astutejoe I have to disagree.  I think it's irresponsible not to lock at the next major version since it represents potentially breaking changes.  Not doing so also recursively breaks all prior versions of your library/framework/app and forces people to hunt down which dependencies would work against any given prior version if they for some reason need to go back to a previous version of your code.  Code should be maintained in a way that guarantees functions as intended at each release.  In other words, your releases should be idempotent.

**Comment by astutejoe** [comment] 2019-03-12 04:49
@josiah14 

> Pipfile.lock
> The Pipfile.lock is intended to specify, based on the packages present in Pipfile, which specific version of those should be used, avoiding the risks of automatically upgrading packages that depend upon each other and breaking your project dependency tree.
> 
> You can lock your currently installed packages using...
> 
> $ pipenv lock
> ... and the tool will lookup your virtual environment folder to generate the lock file for you automatically, based on the currently installed versions. The file syntax is not as obvious as is for Pipfile , so for the sake of conciseness, it will not be displayed here.

[Reference](https://stackoverflow.com/questions/46330327/please-explain-the-usage-of-pipfile-and-pipfile-lock)

**Comment by josiah14** [comment] 2019-03-12 04:51
@astutejoe That doesn't address my argument.  Read what I typed more carefully.

The issue is guaranteeing idempotent builds.  I should be able at any time to go back through your release history and build any release of Flower given the declared dependencies (in this case in requirements.txt files) and have a working instance of the app.

**Comment by astutejoe** [comment] 2019-03-12 04:56
Your argument fundament is about libraries and we're talking about projects, you're drifting from the point to try to sustain your argument. And for projects, yes it does prevent automatic upgrading of your libraries dependencies. As pointed beforehand, managing your libraries versions is your job and you should pinpoint when they are problematic. With both libraries and library dependencies locked, you should be good and have the latest security and performance patches :)

**Comment by josiah14** [comment] 2019-03-12 04:59
I disagree.  As a developer, I should be confident that the build process in the documentation produces a working instance of the application 100% of the time for each release, especially for open source which is likely to have other people wishing to contribute from outside the core team.

I would expect maybe the development branch (in this case, I consider master to be a development branch) to be less stable since it represents a work-in-progress, but releases should be cut and stable.

**Comment by astutejoe** [comment] 2019-03-12 05:00
I think it's clear we're not talking about open source projects :/

**Comment by josiah14** [comment] 2019-03-12 05:00
Is Flower not open source?

**Comment by josiah14** [comment] 2019-03-12 05:08
I'm really not trying to be difficult, here.  I just don't understand this mentality that I seem to be encountering, that it's okay to write things in a way that we are actively aware is likely to cause previous release to stop working as written.  This doesn't make sense to me at all...

**Comment by josiah14** [comment] 2019-03-12 05:26
I don't want to cause any enmity with the people here, so at this point if my point still isn't understood, or if people see it and still disagree, I'm not going to pursue my side of the argument any further.

**Comment by josiah14** [comment] 2019-03-12 11:32
@browniebroke That's my hope, as well, that this is understood as a healthy disagreement in philosophy and we all come away from this with mutual respect for each other.  It appears to me that this is more of a disagreement in value: stability vs being able to surf along the bleeding edge of the latest changes on each dependency (and which should take precedence over the other).  It's not my place to decide where the community's values on a project should be, so I have no issue with conceding in this case.

I don't work exclusively in Python (far from it), so I'm probably bringing along with me the cultural values I've subconsciously picked-up from other languages.

**Comment by mher** [comment] 2019-03-16 22:26
A new flower version has been uploaded to pypi

**Closed by mher** 2019-03-16 22:26 UTC

**Comment by rajreddy251** [comment] 2019-04-02 13:01
has the fix is being released for this issue?
I am migrating my project from python 2.7 to python 3.6 and earlier I was running with tornado 5.1. 

There seems to be a bug with log_exception in one of stackoverflow thread I have created [Earlier Error is AttributeError: 'WebSocketClientConnection' object has no attribute 'log_exception']. This bug seems to have resolved in tornado v6. 

now upgrade to v6 gets failed with 
`   @tornado.web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'` below exception. 

Pls let me know how to get the fix for this?

**Comment by ayushi-singhal** [comment] 2024-02-19 18:47
Hey I have faced one issue.

I need to update Tornado lib version(in requirements.txt) via flower lib version(in requirements.in). 
I have updated flower version and ran cmds `pip-compile --output-file requirements.txt requirements.in` and `pip install -r packages/shared/requirements/requirements.txt`. But I do not see tornado version getting upgraded. 

What steps am I missing here?
