### ISSUE TITLE
Installing the latest release version 0.9.2 fails with Python 2

### ISSUE THREAD

**Issue by pbasista** [mher/flower#882] opened 2019-03-05 09:36 UTC
Installing `flower==0.9.2` in a Python 2 virtual environment fails because of unsatisfied dependencies:

```shell
$ pip install flower==0.9.2
...
tornado requires Python '>= 3.5' but the running Python is 2.7.15
```

The reason is that Tornado 6, which drops support for Python 2, has recently been [released](https://github.com/tornadoweb/tornado/blob/master/docs/releases/v6.0.0.rst#backwards-incompatible-changes). At the same time, the currently latest release version of Flower, namely 0.9.2, does _not_ have an upper bound restriction on `tornado` version:
https://github.com/mher/flower/blob/f44485ca57ef05380f4d4a4ee81183b339c29737/requirements/default.txt#L2

I think that it would be reasonable to either release a bugfix version that addresses this or move on with the release of version 1.

**Comment by zachliu** [comment] 2019-03-05 15:27
I have a very similar issue. Before Mar 3, 2019. `flower==0.9.2` uses `tornado-5.1.1`. Now, it uses `tornado-6.0.1` which is not compatible. I got this error:
```
Starting flower
Traceback (most recent call last):
File "/usr/local/bin/flower", line 7, in <module>
from flower.__main__ import main
File "/usr/local/lib/python2.7/dist-packages/flower/__main__.py", line 4, in <module>
from flower.command import FlowerCommand
File "/usr/local/lib/python2.7/dist-packages/flower/command.py", line 12, in <module>
from tornado.options import options
File "/usr/local/lib/python2.7/dist-packages/tornado/options.py", line 127
def __init__(self) -> None:
^
SyntaxError: invalid syntax
```

**Comment by mher** [comment] 2019-03-16 22:25
Duplicate of #886

**Closed by mher** 2019-03-16 22:25 UTC
