### ISSUE TITLE
Due to a celery update, Flower is unable to perform the following action: From Celery. Bin. Base Import Command

### ISSUE THREAD

**Issue by YihuiLu** [mher/flower#1033] opened 2020-10-12 03:34 UTC
```
$ flower -A celery_app.worker:celery --port=7779
Traceback (most recent call last):
  File "/Users/luyifei/.local/share/virtualenvs/natural-language-processing-M90GmBdj/bin/flower", line 5, in <module>
    from flower.__main__ import main
  File "/Users/luyifei/.local/share/virtualenvs/natural-language-processing-M90GmBdj/lib/python3.8/site-packages/flower/__main__.py", line 4, in <module>
    from flower.command import FlowerCommand
  File "/Users/luyifei/.local/share/virtualenvs/natural-language-processing-M90GmBdj/lib/python3.8/site-packages/flower/command.py", line 17, in <module>
    from celery.bin.base import Command
ImportError: cannot import name 'Command' from 'celery.bin.base' (/Users/luyifei/.local/share/virtualenvs/natural-
```

```
$ celery --version
5.0.0 (singularity)

$ python --version
Python 3.8.4

flower==0.9.5
```

**Comment by YihuiLu** [comment] 2020-10-12 05:49
I choose to downgrade celery

**Comment by dkdndes** [comment] 2021-01-02 20:01
@YihuiLu please reopen it, it's still wrong in the current version.

**Comment by mher** [comment] 2021-01-05 14:43
Duplicate of https://github.com/mher/flower/issues/1029

**Closed by mher** 2021-01-05 14:43 UTC
Labels: bug
