### ISSUE TITLE
Error when connecting to redis through unix socket

### ISSUE THREAD

**Issue by MJafarMashhadi** [mher/flower#638] opened 2016-11-18 21:04 UTC
Shows me this error when i try to use redis+socket:///.....

    'redis' broker is not supported

tried both `--broker` and `--broker_api`

(Saw #401)

**Comment by mher** [comment] 2017-01-31 05:43
Duplicate of #401

**Closed by mher** 2017-01-31 05:43 UTC
Labels: duplicate

**Comment by MJafarMashhadi** [comment] 2017-01-31 20:34
It's good to notice that I saw #401, emphasized on this in my issue text and believe that they are two different issues.
