### ISSUE TITLE
KeyError on tasks tab

### ISSUE THREAD

**Issue by azurda** [mher/flower#669] opened 2017-02-20 11:32 UTC
I leave the stacktrace, got any idea what could be happening? 

`    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2717, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/flower/views/tasks.py", line 28, in get
        self.render("task.html", task=task)
      File "/usr/local/lib/python2.7/dist-packages/flower/views/__init__.py", line 21, in render
        super(BaseHandler, self).render(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 704, in render
        html = self.render_string(template_name, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 811, in render_string
        return t.generate(**namespace)
      File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 278, in generate
        return execute()
      File "task_html.generated.py", line 197, in _tt_execute
        if name not in ['name', 'uuid', 'state', 'args', 'kwargs', 'result'] and getattr(task, name, None) is not None:  # task.html:68 (via base.html:55)
      File "/usr/local/lib/python2.7/dist-packages/kombu/utils/objects.py", line 44, in __get__
        value = obj.__dict__[self.__name__] = self.__get(obj)
      File "/usr/local/lib/python2.7/dist-packages/celery/events/state.py", line 391, in root
        return self.root_id and self.cluster_state.tasks[self.root_id]
      File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py", line 65, in __getitem__
        value = self[key] = self.data.pop(key)
      File "/usr/lib/python2.7/collections.py", line 160, in pop
        raise KeyError(key)
    KeyError: u'5086dda2-9958-4452-b6c5-2cf5ae8b9114'

`

**Comment by mher** [comment] 2017-03-18 22:05
Duplicate of https://github.com/mher/flower/issues/679

**Comment by ineedblood** [comment] 2017-04-20 08:52
I fixed this with... git+http://github.com/Eugeny/celery#egg=celery==4.0.2.1
in case it helps someone

**Comment by johnarnold** [comment] 2017-07-19 19:00
@ineedblood which commit?

**Closed** 2020-04-17 03:41 UTC
Labels: tasks
