### ISSUE TITLE
url_prefix option is not supported anymore

### ISSUE THREAD

**Issue by kaushalsingh11** [mher/flower#390] opened 2015-04-29 10:28 UTC
Have Installed flower via pip. This is throwing the error: url_prefix option is not supported anymore.
If this option is deprecated? How to achieve this?

**Comment by kneckinator** [comment] 2015-06-02 05:00
Documentation on readthedocs says the option is still available, though I ran into the same problem upgrading from flower==0.6.0 -> 0.8.2

http://flower.readthedocs.org/en/latest/man.html?highlight=url_prefix

**Comment by jeromedoyle** [comment] 2015-06-23 16:33
Any updates on this?

**Comment by mher** [comment] 2015-07-25 23:26
Duplicate of #414

**Closed by mher** 2015-07-25 23:26 UTC
Labels: duplicate
