### ISSUE TITLE
Github Auth not working on Python3

### ISSUE THREAD

**Issue by alexkiro** [mher/flower#622] opened 2016-10-06 19:32 UTC
When trying Github Auth, in a Python 3 environment. This issues does not occur on Python 2

```
flower   -> flower:0.9.1 tornado:4.2 babel:2.3.4
software -> celery:3.1.23 (Cipater) kombu:3.0.34 py:3.5.1+
            billiard:3.3.0.23 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

CELERY_DISABLE_RATE_LIMITS: True
CELERY_IGNORE_RESULT: True
BROKER_URL: 'redis+socket:///var/run/redis/redis.sock?virtual_host=1'
CELERY_ACCEPT_CONTENT: ['json']
CELERYBEAT_SCHEDULE: {
    'expire_data': {   'schedule': <crontab: 0 1 * * * (m/h/d/dM/MY)>,
                       'task': 'smbh.singularity.expire_data'}}
CELERYD_PREFETCH_MULTIPLIER: 100
BROKER_POOL_LIMIT: 100

Traceback (most recent call last):
  File "/var/cache/smbh-env/lib/python3.5/site-packages/tornado/web.py", line 1369, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 3, in raise_exc_info
  File "/var/cache/smbh-env/lib/python3.5/site-packages/tornado/web.py", line 1572, in wrapper
    result = method(self, *args, **kwargs)
  File "/var/cache/smbh-env/lib/python3.5/site-packages/flower/views/auth.py", line 106, in _on_access_token
    future.set_result(json.loads(response.body))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by mhelmer** [comment] 2016-10-10 05:20
Duplicate of #616

**Comment by MJafarMashhadi** [comment] 2016-11-18 21:07
As  a workaround you can open `flower/views/auth.py` in an editor and change 106th line to:

        future.set_result(json.loads(response.body.decode('utf-8')))

**Comment by mher** [comment] 2016-11-18 23:30
Fixed by https://github.com/mher/flower/pull/635

**Closed** 2017-01-10 00:26 UTC
