### ISSUE TITLE
Installing with pip uninstall celery 5.0.5 and install celery-4.4.7

### ISSUE THREAD

**Issue by serker72** [mher/flower#1082] opened 2021-03-25 13:50 UTC
**Describe the bug**
Installing with pip uninstall celery 5.0.5 and install celery-4.4.7

**To Reproduce**
1. Go to terminal
2. Run pip install flower
3. See error
#pip install flower
Collecting flower
  Downloading flower-0.9.7-py2.py3-none-any.whl (456 kB)
     |████████████████████████████████| 456 kB 1.3 MB/s 
Collecting humanize
  Downloading humanize-3.3.0-py3-none-any.whl (70 kB)
     |████████████████████████████████| 70 kB 927 kB/s 
Collecting prometheus-client==0.8.0
  Downloading prometheus_client-0.8.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 280 kB/s 
Collecting celery<5.0.0,>=4.3.0
  Downloading celery-4.4.7-py2.py3-none-any.whl (427 kB)
     |████████████████████████████████| 427 kB 5.3 MB/s 
Collecting vine==1.3.0
  Downloading vine-1.3.0-py2.py3-none-any.whl (14 kB)
Collecting tornado<7.0.0,>=5.0.0
  Downloading tornado-6.1-cp38-cp38-manylinux2010_x86_64.whl (427 kB)
     |████████████████████████████████| 427 kB 6.1 MB/s 
Requirement already satisfied: pytz in /home/serg/.virtualenvs/vacations/lib/python3.8/site-packages (from flower) (2020.1)
Collecting kombu<4.7,>=4.6.10
  Downloading kombu-4.6.11-py2.py3-none-any.whl (184 kB)
     |████████████████████████████████| 184 kB 6.2 MB/s 
Requirement already satisfied: billiard<4.0,>=3.6.3.0 in /home/serg/.virtualenvs/vacations/lib/python3.8/site-packages (from celery<5.0.0,>=4.3.0->flower) (3.6.3.0)
Collecting amqp<2.7,>=2.6.0
  Downloading amqp-2.6.1-py2.py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 546 kB/s 
Requirement already satisfied: setuptools in /home/serg/.virtualenvs/vacations/lib/python3.8/site-packages (from humanize->flower) (45.2.0)
Installing collected packages: vine, amqp, kombu, tornado, prometheus-client, humanize, celery, flower
  Attempting uninstall: vine
    Found existing installation: vine 5.0.0
    Uninstalling vine-5.0.0:
      Successfully uninstalled vine-5.0.0
  Attempting uninstall: amqp
    Found existing installation: amqp 5.0.5
    Uninstalling amqp-5.0.5:
      Successfully uninstalled amqp-5.0.5
  Attempting uninstall: kombu
    Found existing installation: kombu 5.0.2
    Uninstalling kombu-5.0.2:
      Successfully uninstalled kombu-5.0.2
  Attempting uninstall: celery
    Found existing installation: celery 5.0.5
    Uninstalling celery-5.0.5:
      Successfully uninstalled celery-5.0.5
Successfully installed amqp-2.6.1 celery-4.4.7 flower-0.9.7 humanize-3.3.0 kombu-4.6.11 prometheus-client-0.8.0 tornado-6.1 vine-1.3.0

**Expected behavior**
Work with celery 5.0.5

**System information**
flower   -> flower:0.9.7 tornado:6.1 humanize:3.3.0
software -> celery:4.4.7 (cliffs) kombu:4.6.11 py:3.8.6
            billiard:3.6.3.0 py-amqp:2.6.1
platform -> system:Linux arch:64bit, ELF
            kernel version:5.4.0-70-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

**Comment by mher** [comment] 2021-03-25 13:58
Duplicate of #1029

**Closed by mher** 2021-03-25 13:58 UTC
Labels: bug
