### ISSUE TITLE
exception raised after search

### ISSUE THREAD

**Issue by rails-to-cosmos** [mher/flower#516] opened 2016-01-18 14:06 UTC
flower   -> flower:0.8.3 tornado:4.3 babel:2.1.1
software -> celery:3.1.19 (Cipater) kombu:3.0.30 py:2.7.6
            billiard:3.3.0.21 py-amqp:1.4.8
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

CELERY_QUEUES: 
    (<unbound Queue save -> <unbound Exchange save(direct)> -> save>,
 <unbound Queue change_status -> <unbound Exchange change_status(direct)> -> change_status>,
 <unbound Queue controller -> <unbound Exchange controller(direct)> -> controller>)
CELERY_ACKS_LATE: True
CELERY_DISABLE_RATE_LIMITS: True
CELERY_ACCEPT_CONTENT: ['json', 'yaml', 'msgpack', 'pickle']
CELERY_IGNORE_RESULT: True
CELERY_MAX_CACHED_RESULTS: 1
CELERY_TASK_RESULT_EXPIRES: 10
CELERY_ROUTES: {
    'crawler.crawler_tasks.schedule': {   'queue': 'schedule',
                                          'routing_key': '********'},
    'crawler.server_tasks.controller': {   'queue': 'controller',
                                           'routing_key': '********'},
    'server_tasks.change_status': {   'queue': 'change_status',
                                      'routing_key': '********'}}
CELERY_DEFAULT_QUEUE: 'server'
CELERYD_PREFETCH_MULTIPLIER: 1
BROKER_URL: 'amqp://cs-server:********@192.168.69.180:5672/server'
CELERYD_POOL_RESTARTS: True

Traceback (most recent call last):
  File "/home/user/projects/cs_env/local/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/user/projects/cs_env/local/lib/python2.7/site-packages/tornado/web.py", line 2800, in wrapper
    return method(self, *args, **kwargs)
  File "/home/user/projects/cs_env/local/lib/python2.7/site-packages/flower/views/tasks.py", line 88, in get
    search=search
  File "/home/user/projects/cs_env/local/lib/python2.7/site-packages/flower/views/__init__.py", line 20, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/home/user/projects/cs_env/local/lib/python2.7/site-packages/tornado/web.py", line 699, in render
    html = self.render_string(template_name, **kwargs)
  File "/home/user/projects/cs_env/local/lib/python2.7/site-packages/tornado/web.py", line 806, in render_string
    return t.generate(**namespace)
  File "/home/user/projects/cs_env/local/lib/python2.7/site-packages/tornado/template.py", line 345, in generate
    return execute()
  File "tasks_html.generated.py", line 225, in _tt_execute
    for uuid, task in tasks:  # tasks.html:151 (via base.html:49)
  File "/home/user/projects/cs_env/local/lib/python2.7/site-packages/flower/utils/tasks.py", line 46, in iter_tasks
    if not satisfies_search_terms(task, any_value_search_term, result_search_term, args_search_terms, kwargs_search_terms):
  File "/home/user/projects/cs_env/local/lib/python2.7/site-packages/flower/utils/search.py", line 32, in satisfies_search_terms
    any_value_search_term and any_value_search_term in '|'.join([task.args, task.kwargs, str(task.result)]),
TypeError: sequence item 0: expected string, NoneType found

**Comment by mher** [comment] 2016-01-18 21:37
Duplicate of #480

**Closed by mher** 2016-01-18 21:37 UTC
