### ISSUE TITLE
cannot import name 'Command' from 'celery.bin.base'

### ISSUE THREAD

**Issue by gongxiujin** [mher/flower#1031] opened 2020-09-28 07:57 UTC
steps:
1. ```pip install -U Celery```
2. ```pip install flower```
3.  When  I execute ```flower --version``` or ``` flower --address=0.0.0.0 --port=5555``` get error:

```
Traceback (most recent call last):
  File "XXXXXXXXXXX/.env/bin/flower", line 6, in <module>
    from flower.__main__ import main
  File "/XXXXXXXXXXX//.env/lib/python3.7/site-packages/flower/__main__.py", line 4, in <module>
    from flower.command import FlowerCommand
  File "/XXXXXXXXXXX/.env/lib/python3.7/site-packages/flower/command.py", line 17, in <module>
    from celery.bin.base import Command
ImportError: cannot import name 'Command' from 'celery.bin.base' (/XXXXXXXXXXX//.env/lib/python3.7/site-packages/celery/bin/base.py)
```
use Vitualenv, ```celery==5.0.0;celery-flower==1.0.1```

**Comment by mher** [comment] 2020-09-28 08:02
Duplicate of #1029

**Closed by mher** 2020-09-28 08:02 UTC
Labels: bug, duplicate
