### ISSUE TITLE
GET /api/task/info/(.*) results in 404s if task has been retried

### ISSUE THREAD

**Issue by BjBlazkowicz** [mher/flower#664] opened 2017-01-30 13:35 UTC
Seems like a bug.

Tasks that has been retried keeps the same ID so this should not happen.

Flower version used: 0.8.4

**Comment by rafaelreuber** [comment] 2017-03-24 18:30
Have you tried to reproduce de this bug using the version 0.9.1?

**Comment by anilpai** [comment] 2017-08-25 21:22
/api/task/info gives 500 Server Error . This is a known open bug. https://github.com/mher/flower/issues/617

**Comment by anilpai** [comment] 2017-10-09 17:02
This bug is fixed now on master, but since I was using 0.92 release, it was giving me this error. Looking forward to next release.

**Closed** 2020-07-05 22:05 UTC
Labels: api
